return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.14.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 30,
  tilewidth = 16,
  tileheight = 16,
  nextobjectid = 17,
  properties = {},
  tilesets = {
    {
      name = "Sprite-0001",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      image = "Sprite-0001.png",
      imagewidth = 128,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 64,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "タイル・レイヤー 2",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAIwAAACQAAAAjAAAAJAAAACMAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAABsAAAAcAAAAGwAAABwAAAAbAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    {
      type = "tilelayer",
      name = "タイル・レイヤー 1",
      x = 0,
      y = 0,
      width = 40,
      height = 30,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "IQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUAAAAWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAANAAAADgAAAA0AAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAFQAAABYAAAAVAAAAFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAAhAAAAIgAAACEAAAAiAAAAIQAAACIAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAAKQAAACoAAAApAAAAKgAAACkAAAAqAAAA"
    },
    {
      type = "objectgroup",
      name = "block",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 128,
          width = 32,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 128,
          width = 32,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 352,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 128,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 288,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 320,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "door",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 2,
          name = "1",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 336,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["num"] = "1",
            ["room"] = "debug1"
          }
        },
        {
          id = 3,
          name = "2",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 336,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {
            ["num"] = "1",
            ["room"] = "debug3"
          }
        }
      }
    }
  }
}
